# Generated by Django 5.1.1 on 2024-10-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0002_alter_task_options_remove_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Finished', 'Finished')], default='To do', max_length=50),
        ),
    ]
