# Generated by Django 5.1.1 on 2024-10-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0007_remove_task_archived_task_color_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Finished', 'Finished'), ('On hold', 'On hold')], max_length=15),
        ),
    ]
